import Head from 'next/head'
import { Inter } from '@next/font/google'
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import { useState } from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Abdul Khaliq</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className=' py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white uppercase'>Nexon</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)} className=' cursor-pointer text-xl dark:text-white' />
              </li>
              <li><a className=' bg-gradient-to-t from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className=' text-center p-10'>
            <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Abdul Khaliq</h2>
            <h3 className=' text-2xl py-2 md:text-3xl dark:text-white'>Front and Backend Developer</h3>
            <p className=' text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum aut distinctio earum nesciunt rerum eaque corporis id? In, placeat aliquam.</p>
          </div>
          <div className=' text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className=' relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
            <Image src={deved} layout='fill' objectFit='cover' />
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Services I offer</h3>
            <p className=' text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem qui numquam possimus perspiciatis ratione officiis deserunt minus quas explicabo recusandae?</p>
          </div>
          <div className='lg:flex gap-10 '>
            <div className=' text-center shadow-lg p-10 rounded-lg my-10 dark:bg-white'>
              <Image className='mx-auto' src={design} width={100} height={100} />
              <h3 className='text-lg font-me pt-8 pb-2'>Beautiful designs</h3>
              <p className='py-2'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium, recusandae?</p>
              <h4 className='py-4 text-teal-600'>Design Tools</h4>
              <p className=' text-gray-800 py-1'>Photoshop</p>
              <p className=' text-gray-800 py-1'>Illustrator</p>
              <p className=' text-gray-800 py-1'>Figma</p>
            </div>
            <div className=' text-center shadow-lg p-10 rounded-lg my-10 dark:bg-white'>
              <Image className='mx-auto' src={code} width={100} height={100} />
              <h3 className='text-lg font-me pt-8 pb-2'>Beautiful designs</h3>
              <p className='py-2'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium, recusandae?</p>
              <h4 className='py-4 text-teal-600'>Design Tools</h4>
              <p className=' text-gray-800 py-1'>Photoshop</p>
              <p className=' text-gray-800 py-1'>Illustrator</p>
              <p className=' text-gray-800 py-1'>Figma</p>
            </div>
            <div className=' text-center shadow-lg p-10 rounded-lg my-10 dark:bg-white'>
              <Image className='mx-auto' src={consulting} width={100} height={100} />
              <h3 className='text-lg font-me pt-8 pb-2'>Beautiful designs</h3>
              <p className='py-2'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium, recusandae?</p>
              <h4 className='py-4 text-teal-600'>Design Tools</h4>
              <p className=' text-gray-800 py-1'>Photoshop</p>
              <p className=' text-gray-800 py-1'>Illustrator</p>
              <p className=' text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className=' text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className=' text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam sunt optio voluptate earum minus eveniet neque velit iste deleniti, officia minima blanditiis quidem eum beatae quasi voluptatum natus consequatur dolorem?</p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basic-1/3 flex-1'><Image className='rounded-lg object-cover'  src={web1} width={'100%'} height={'100%'} layout="responsive"/></div>
            <div className='basic-1/3 flex-1'><Image className='rounded-lg object-cover'  src={web2} width={'100%'} height={'100%'} layout="responsive"/></div>
            <div className='basic-1/3 flex-1'><Image className='rounded-lg object-cover'  src={web3} width={'100%'} height={'100%'} layout="responsive"/></div>
            <div className='basic-1/3 flex-1'><Image className='rounded-lg object-cover'  src={web4} width={'100%'} height={'100%'} layout="responsive"/></div>
            <div className='basic-1/3 flex-1'><Image className='rounded-lg object-cover'  src={web5} width={'100%'} height={'100%'} layout="responsive"/></div>
          </div>
        </section>
      </main>
    </div>
  )
}
